on:
  workflow_call:
    inputs:
      string:
        required: true
        type: string
      env:
        required: true
        type: string
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-step
        run: echo first ${{ inputs.string }}
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    environment: ${{ inputs.env }}
    steps:
      - name: first-step
        run: echo second ${{ inputs.string }}
