name: Minimal Environment Matrix
run-name: ${{ github.ref_name }} - ${{ github.event.head_commit.message }} 🚀
on: [push]
jobs:
  Set_Matrix_Output:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.set-environment.outputs.environments }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - id: set-environment
        run: |
          JSON="$(cat simple.json | tr '\n' ' ')"
          echo "environments=${JSON}" >> $GITHUB_OUTPUT
  Env-Matrix-Job:
    runs-on: ubuntu-latest
    needs: Set_Matrix_Output
    environment: ${{ matrix.environments.id }}
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.Explore-GitHub-Actions.outputs.environments)}}
    steps:
      - run: echo "Environment is ${{ matrix.environments.name }}, layers are ${{ matrix.environments.layers}}"
